- name: Update package registry
  apt:
    update_cache: true

- name: install nginx
  apt:
    name: nginx
    state: latest

- name: Enable ufw access for Nginx Full
  ufw:
    rule: allow
    name: "Nginx Full"

- name: create /etc/letsencrypt
  file: path=/etc/letsencrypt state=directory recurse=yes

- name: copy cloudflare.ini
  template: src=cloudflare.ini.j2 dest=/etc/letsencrypt/cloudflare.ini

- name: install pip3
  apt: name=python3-pip state=present

- name: install certbot and certbot-dns-cloudflare
  command: pip3 install certbot 'zope.interface>=5.3.0a1' certbot-dns-cloudflare

- name: run certbot
  command: certbot certonly --dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini --email '{{ email }}' --domain '*.{{ domain_name }}' --agree-tos --non-interactive

- name: copy nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf mode=preserve
  notify: restart nginx

- name: start nginx
  ansible.builtin.service:
    name: nginx
    state: started
